"""Switch to Supabase Storage

Revision ID: 153dd14d9bde
Revises: fcdc8278d54d
Create Date: 2025-12-05 09:45:00.630541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '153dd14d9bde'
down_revision: Union[str, Sequence[str], None] = 'fcdc8278d54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_responses_id'), table_name='test_responses')
    op.drop_table('test_responses')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('idx_submissions_assignment_id'), table_name='submissions')
    op.alter_column('test_assignments', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_assignments_candidate_id'), table_name='test_assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_assignments_candidate_id'), 'test_assignments', ['candidate_id'], unique=False)
    op.alter_column('test_assignments', 'scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('idx_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('encrypted_options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_answer_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('test_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_submission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('test_responses_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_responses_pkey'))
    )
    op.create_index(op.f('ix_test_responses_id'), 'test_responses', ['id'], unique=False)
    # ### end Alembic commands ###
